### ISSUE TITLE
Create About Us Page

### ISSUE THREAD

**Issue by takumab** [BlackDevsUK/website#24]
**Goal of About Page**
- More in-depth Intro of what BDUK is about to potential members
- More in-depth of what BDUK is about to potential sponsors
- Upcoming events

## Summary
As a first time visiter, I want to know more of what BDUK is about so that I can decide if I want to become a member or a sponsor

### Scenario: User visits `blackdevs.uk/about`
**Given** that I as a user visit `blackdevs.uk/about`
**When** I get to the about page
**Then** I can read a more detailed introduction of what  BDUK is about.

## Additional context
Add any other context or screenshots for the user story here.

**Comment by MrHunte** [comment]
UK Black Devs - About page



UK Black Devs is a community of Black software developers/engineers form around the UK, with a shared passion for development. The community is compromised of members looking to begin their development/engineering journey to seasoned professionals.

The focus of the community is to collabortion and support regardless of your technical ability of preferred tech stack.

With monthly socials and an inclusive Slack channel, this is a fantastic place to collaborate, share ideas, receive support and discuss the latest trends within the industry. 

**_Section about what makes BDUK unique_**
