### ISSUE TITLE
Research CMS platforms

### ISSUE THREAD

**Issue by Genyus** [BlackDevsUK/website#9]
Investigate pricing, functionality, platform compatibility of compatible CMS platforms, e.g. Contentful, NetlifyCMS, etc

**Comment by colin123456** [comment]
Can we add 
https://graphcms.com/ to this list as well. 
Free for up to 5 users and 2 locales per project

**Comment by Safiyya** [comment]
**Sanity.io**
Free up to 3 users, 10k documents
5GB Assets
Very useful CLI
